### ISSUE TITLE
Only JSON responses are registered

### ISSUE THREAD

**Issue by immanuelfodor** [Treblle/TreblleTraefikPluginGo#12]
Testing the plugin, it seems response data is only registered if the response is JSON.

Using a simple [whoami](https://github.com/traefik/whoami) application, the default text response does not appear on the Treblle online dashboard. The only time the response shows up is if the response is JSON.

Is there a limitation, a bug, or a missing configuration somewhere? 

---

How to reproduce:

<details>
<summary>Config and commands to use</summary>

```yaml
# Install Hub as usual, then:
# helm upgrade traefik -n traefik --reuse-values --set logs.general.level=INFO --set persistence.enabled=true --set persistence.path=/plugins-storage --set podSecurityContext.fsGroup=65532 --set podSecurityContext.fsGroupChangePolicy=OnRootMismatch --set additionalArguments='{--experimental.plugins.treblle.moduleName=github.com/Treblle/TreblleTraefikPluginGo,--experimental.plugins.treblle.version=v1.0.3}' traefik/traefik
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: treblle
spec:
  plugin:
    treblle:
      ApiKey: "XXX"
      ProjectId: "XXX"
      # AdditionalFieldsToMask:
      #   - "accessToken"
      #   - "refreshToken"
      # RoutesToBlock:
      #   - "/api/user/login"
      #   - "/ping"
      # RoutesRegex: "^/api/projects"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: default-treblle@kubernetescrd
spec:
  rules:
    - host: whoami.docker.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
# curl -i http://whoami.docker.localhost
```

</details>
